steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.production
      - -t
      - $_REGION-docker.pkg.dev/$PROJECT_ID/docker-repo/just-task-it:$SHORT_SHA
      - -t
      - $_REGION-docker.pkg.dev/$PROJECT_ID/docker-repo/just-task-it:latest
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_REGION-docker.pkg.dev/$PROJECT_ID/docker-repo/just-task-it:$SHORT_SHA

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_REGION-docker.pkg.dev/$PROJECT_ID/docker-repo/just-task-it:latest

  - name: gcr.io/cloud-builders/kubectl
    args:
      - apply
      - -k
      - infra/k8s/overlays/prod/
    env:
      - CLOUDSDK_COMPUTE_REGION=$_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=gke-2dv013-prod

images:
  - $_REGION-docker.pkg.dev/$PROJECT_ID/docker-repo/just-task-it:$SHORT_SHA
  - $_REGION-docker.pkg.dev/$PROJECT_ID/docker-repo/just-task-it:latest

substitutions:
  _REGION: europe-west4

options:
  machineType: N1_HIGHCPU_8
