steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.production
      - -t
      - $_REGION-docker.pkg.dev/$PROJECT_ID/docker-repo/just-task-it:$SHORT_SHA
      - -t
      - $_REGION-docker.pkg.dev/$PROJECT_ID/docker-repo/just-task-it:latest
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_REGION-docker.pkg.dev/$PROJECT_ID/docker-repo/just-task-it:$SHORT_SHA

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_REGION-docker.pkg.dev/$PROJECT_ID/docker-repo/just-task-it:latest

  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        # Install kompose
        curl -sSLo /usr/local/bin/kompose https://github.com/kubernetes/kompose/releases/latest/download/kompose-linux-amd64
        chmod +x /usr/local/bin/kompose
        
        # Generate Kubernetes manifests from docker-compose
        rm -rf infra/k8s/generated
        mkdir -p infra/k8s/generated
        kompose convert -f docker-compose.yaml --namespace $_NAMESPACE -o infra/k8s/generated
        
        # Update just-task-it image in generated manifest
        for manifest in infra/k8s/generated/just-task-it-*.yaml; do
          if [ -f "$$manifest" ]; then
            echo "Updating manifest: $$manifest"
            sed -i "s|image: just-task-it:latest|image: $_REGION-docker.pkg.dev/$PROJECT_ID/docker-repo/just-task-it:$SHORT_SHA|g" "$$manifest"
            sed -i "s|value: secret|value: \"$$SESSION_SECRET\"|g" "$$manifest"
            sed -i '/kompose.image-pull-policy/d' "$$manifest"
            echo "Environment variables in manifest:"
            grep -A 2 "RABBITMQ" "$$manifest" || echo "WARNING: RABBITMQ env vars not found!"
            break
          fi
        done
        
        # Fix Grafana permissions
        if [ -f infra/k8s/generated/grafana-deployment.yaml ]; then
          sed -i '/^      containers:/i\      securityContext:\n        fsGroup: 472' infra/k8s/generated/grafana-deployment.yaml
        fi
        
        # Convert kompose-generated LoadBalancer service to ClusterIP (we use base/ingress.yaml LoadBalancer instead)
        if [ -f infra/k8s/generated/just-task-it-service.yaml ]; then
          sed -i 's/type: LoadBalancer/type: ClusterIP/g' infra/k8s/generated/just-task-it-service.yaml
        fi
        
        # Deploy to GKE
        gcloud container clusters get-credentials gke-2dv013-prod --zone=$_ZONE
        kubectl apply -f infra/k8s/base/namespace.yaml
        kubectl delete pod/just-task-it -n $_NAMESPACE --ignore-not-found || true
        if ls infra/k8s/generated/*.yaml >/dev/null 2>&1; then
          kubectl apply -n $_NAMESPACE -f infra/k8s/generated
        fi
        
        # Delete any existing kompose-generated LoadBalancer service to avoid conflicts
        kubectl delete svc just-task-it -n $_NAMESPACE --ignore-not-found || true
        
        # Apply base manifests (LoadBalancers, Ingress, HPA)
        kubectl apply -n $_NAMESPACE -f infra/k8s/base/ingress.yaml || true
        kubectl apply -n $_NAMESPACE -f infra/k8s/base/grafana-ingress.yaml || true
        kubectl apply -n $_NAMESPACE -f infra/k8s/base/hpa.yaml || true
        
        # Wait for deployment to stabilize
        sleep 10
        
        # Verify deployment
        echo "=== POD STATUS ==="
        kubectl -n $_NAMESPACE get pods -o wide || true
        
        echo ""
        echo "=== EVENTS ==="
        kubectl -n $_NAMESPACE get events --sort-by=.lastTimestamp | tail -n 30 || true
        
        echo ""
        echo "=== DEPLOYMENT STATUS (just-task-it) ==="
        kubectl -n $_NAMESPACE get deployment just-task-it -o wide || true
        
        echo ""
        echo "=== APP POD LOGS ==="
        kubectl -n $_NAMESPACE logs deployment/just-task-it --tail=50 --all-containers || true
        
        echo ""
        echo "=== SERVICES ==="
        kubectl -n $_NAMESPACE get svc -o wide || true
        
        echo ""
        echo "=== DEPLOYMENT COMPLETE ==="
    env:
      - CLOUDSDK_COMPUTE_REGION=$_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=gke-2dv013-prod
      - NAMESPACE=$_NAMESPACE
    secretEnv:
      - SESSION_SECRET

images:
  - $_REGION-docker.pkg.dev/$PROJECT_ID/docker-repo/just-task-it:$SHORT_SHA
  - $_REGION-docker.pkg.dev/$PROJECT_ID/docker-repo/just-task-it:latest

substitutions:
  _REGION: europe-west4
  _NAMESPACE: just-task-it
  _ZONE: europe-west4-a

options:
  machineType: E2_HIGHCPU_8
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - env: SESSION_SECRET
      versionName: projects/$PROJECT_ID/secrets/SESSION_SECRET/versions/latest
