steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.production
      - -t
      - $_REGION-docker.pkg.dev/$PROJECT_ID/docker-repo/just-task-it:$SHORT_SHA
      - -t
      - $_REGION-docker.pkg.dev/$PROJECT_ID/docker-repo/just-task-it:latest
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_REGION-docker.pkg.dev/$PROJECT_ID/docker-repo/just-task-it:$SHORT_SHA

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_REGION-docker.pkg.dev/$PROJECT_ID/docker-repo/just-task-it:latest

  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - run
      - --filename=infra/k8s/overlays/prod/
      - --image=$_REGION-docker.pkg.dev/$PROJECT_ID/docker-repo/just-task-it:$SHORT_SHA
      - --location=$_REGION
      - --cluster=gke-2dv013-prod
    env:
      - CLOUDSDK_COMPUTE_REGION=$_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=gke-2dv013-prod

  - name: gcr.io/cloud-builders/kubectl
    entrypoint: bash
    args:
      - -c
      - |
        gcloud container clusters get-credentials gke-2dv013-prod --region=$_REGION
        kubectl create secret generic app-secrets \
          --from-literal=session-secret=$$SESSION_SECRET \
          --dry-run=client -o yaml | \
        kubectl apply -f - -n production
    env:
      - CLOUDSDK_COMPUTE_REGION=$_REGION
    secretEnv:
      - SESSION_SECRET

images:
  - $_REGION-docker.pkg.dev/$PROJECT_ID/docker-repo/just-task-it:$SHORT_SHA
  - $_REGION-docker.pkg.dev/$PROJECT_ID/docker-repo/just-task-it:latest

substitutions:
  _REGION: europe-west4

availableSecrets:
  secretManager:
    - env: SESSION_SECRET
      versionName: projects/556283934605/secrets/SESSION_SECRET/versions/latest

options:
  machineType: E2_HIGHCPU_8
  logging: CLOUD_LOGGING_ONLY
