steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.production
      - -t
      - $_REGION-docker.pkg.dev/$PROJECT_ID/docker-repo/just-task-it:$SHORT_SHA
      - -t
      - $_REGION-docker.pkg.dev/$PROJECT_ID/docker-repo/just-task-it:latest
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_REGION-docker.pkg.dev/$PROJECT_ID/docker-repo/just-task-it:$SHORT_SHA

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_REGION-docker.pkg.dev/$PROJECT_ID/docker-repo/just-task-it:latest

  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        # Install kompose
        curl -L https://github.com/kubernetes-kompose/kompose/releases/download/v1.37.0/kompose-linux-amd64 -o /usr/local/bin/kompose
        chmod +x /usr/local/bin/kompose
        
        # Generate Kubernetes manifests from docker-compose
        mkdir -p infra/k8s/base
        kompose convert -f docker-compose.yaml -f docker-compose.production.yaml -o infra/k8s/base/komposed.yaml
        
        # Deploy to GKE
        gcloud container clusters get-credentials gke-2dv013-prod --region=$_REGION
        kubectl apply -k infra/k8s/overlays/prod/
        kubectl set image deployment/just-task-it \
          just-task-it=$_REGION-docker.pkg.dev/$PROJECT_ID/docker-repo/just-task-it:$SHORT_SHA \
          -n production
    env:
      - CLOUDSDK_COMPUTE_REGION=$_REGION

images:
  - $_REGION-docker.pkg.dev/$PROJECT_ID/docker-repo/just-task-it:$SHORT_SHA
  - $_REGION-docker.pkg.dev/$PROJECT_ID/docker-repo/just-task-it:latest

substitutions:
  _REGION: europe-west4

options:
  machineType: E2_HIGHCPU_8
  logging: CLOUD_LOGGING_ONLY
