steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.production
      - -t
      - $_REGION-docker.pkg.dev/$PROJECT_ID/docker-repo/just-task-it:$SHORT_SHA
      - -t
      - $_REGION-docker.pkg.dev/$PROJECT_ID/docker-repo/just-task-it:latest
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_REGION-docker.pkg.dev/$PROJECT_ID/docker-repo/just-task-it:$SHORT_SHA

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_REGION-docker.pkg.dev/$PROJECT_ID/docker-repo/just-task-it:latest

  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        # Install kompose
        curl -sSLo /usr/local/bin/kompose https://github.com/kubernetes/kompose/releases/latest/download/kompose-linux-amd64
        chmod +x /usr/local/bin/kompose
        
        # Generate Kubernetes manifests from docker-compose
        mkdir -p infra/k8s/base
        kompose convert -f docker-compose.yaml --services grafana,influxdb,mongodb,rabbit,redis,telegraf -o infra/k8s/base/generated-services.yaml
        
        # Deploy to GKE
        gcloud container clusters get-credentials gke-2dv013-prod --region=$_REGION
        kubectl apply -k infra/k8s/overlays/prod/
        kubectl create secret generic app-secrets \
          --from-literal=session-secret="$SESSION_SECRET" \
          --dry-run=client -o yaml | kubectl apply -f - -n $NAMESPACE
        kubectl set image deployment/just-task-it \
          just-task-it=$_REGION-docker.pkg.dev/$PROJECT_ID/docker-repo/just-task-it:$SHORT_SHA \
          -n $NAMESPACE
        
        # Wait for deployment to stabilize
        sleep 10
        
        # Verify deployment
        echo "=== POD STATUS ==="
        kubectl -n $NAMESPACE get pods -o wide || true
        
        echo ""
        echo "=== EVENTS ==="
        kubectl -n $NAMESPACE get events --sort-by=.lastTimestamp | tail -n 30 || true
        
        echo ""
        echo "=== DEPLOYMENT STATUS ==="
        kubectl -n $NAMESPACE get deployment just-task-it -o wide || true
        
        echo ""
        echo "=== APP POD LOGS ==="
        kubectl -n $NAMESPACE logs deployment/just-task-it --tail=50 --all-containers || true
        
        echo ""
        echo "=== SERVICES ==="
        kubectl -n $NAMESPACE get svc -o wide || true
        
        echo ""
        echo "=== DEPLOYMENT COMPLETE ==="
    env:
      - CLOUDSDK_COMPUTE_REGION=$_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=gke-2dv013-prod
      - NAMESPACE=production
    secretEnv:
      - SESSION_SECRET

images:
  - $_REGION-docker.pkg.dev/$PROJECT_ID/docker-repo/just-task-it:$SHORT_SHA
  - $_REGION-docker.pkg.dev/$PROJECT_ID/docker-repo/just-task-it:latest

substitutions:
  _REGION: europe-west4

options:
  machineType: E2_HIGHCPU_8
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - env: SESSION_SECRET
      versionName: projects/556283934605/secrets/SESSION_SECRET/versions/latest
