#!/bin/bash

# Local Just Task It deployment script using Kompose and Docker Desktop Kubernetes
set -euo pipefail

NAMESPACE=${NAMESPACE:-just-task-it}
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
KOMPOSE_DIR="$SCRIPT_DIR/kompose"

command -v kubectl >/dev/null 2>&1 || { echo "❌ kubectl is not installed or not in PATH"; exit 1; }
command -v kompose >/dev/null 2>&1 || { echo "❌ kompose is not installed or not in PATH"; exit 1; }

if ! kubectl cluster-info >/dev/null 2>&1; then
  echo "❌ Kubernetes cluster is not accessible"
  echo "💡 Make sure Docker Desktop Kubernetes is enabled"
  exit 1
fi

echo "✅ Kubernetes cluster is accessible"

echo "🐳 Building Docker image..."
docker build -f "$REPO_ROOT/Dockerfile.production" -t just-task-it:latest "$REPO_ROOT"
echo "✅ Image built"

rm -rf "$KOMPOSE_DIR"
mkdir -p "$KOMPOSE_DIR"

echo "🔄 Converting docker-compose.yaml with kompose..."
kompose convert -f "$REPO_ROOT/docker-compose.yaml" -o "$KOMPOSE_DIR"
# Remove the app resources so we can use our curated manifests
rm -f "$KOMPOSE_DIR"/just-task-it* "$KOMPOSE_DIR"/*just-task-it*.yaml 2>/dev/null || true
echo "✅ Kompose manifests generated in $KOMPOSE_DIR"

if ! kubectl get namespace "$NAMESPACE" >/dev/null 2>&1; then
  echo "📦 Creating namespace $NAMESPACE..."
  kubectl create namespace "$NAMESPACE"
fi

echo "🗺️ Applying base configmap..."
kubectl apply -n "$NAMESPACE" -f "$REPO_ROOT/infra/k8s/base/configmap.yaml"

echo "🔐 Creating/updating application secret..."
SESSION_SECRET_VALUE=${SESSION_SECRET:-local-dev-secret}
kubectl create secret generic app-secrets \
  --from-literal=session-secret="$SESSION_SECRET_VALUE" \
  --dry-run=client -o yaml | kubectl apply -n "$NAMESPACE" -f -

echo "📦 Deploying dependencies generated by kompose..."
kubectl apply -n "$NAMESPACE" -f "$KOMPOSE_DIR"

echo "🚀 Deploying Just Task It application..."
kubectl apply -n "$NAMESPACE" -f "$REPO_ROOT/infra/k8s/base/deployment.yaml"
kubectl set image deployment/just-task-it just-task-it=just-task-it:latest -n "$NAMESPACE"

cat <<"EOF" | kubectl apply -n "$NAMESPACE" -f -
apiVersion: v1
kind: Service
metadata:
  name: just-task-it-service
spec:
  type: NodePort
  selector:
    app: just-task-it
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30080
EOF

echo "✅ Deployment completed!"

echo "📊 Deployment Status:"
kubectl get pods -n "$NAMESPACE"
kubectl get svc -n "$NAMESPACE"

echo ""
echo "🔗 Access your Just Task It at http://localhost:30080"
echo "📝 To tail logs: kubectl logs -f deployment/just-task-it -n $NAMESPACE"
echo ""