name: Terraform Destroy GKE

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Generate env.tfvars
        run: |
          cat > infra/terraform/gke/env.tfvars <<EOF
          project_id   = "${{ secrets.GCP_PROJECT_ID }}"
          project_name = "${{ secrets.GCP_PROJECT_NAME }}"
          region       = "${{ secrets.GCP_REGION }}"
          EOF

      - name: Terraform init
        run: terraform init -backend-config="bucket=${{ secrets.GCP_BUCKET_NAME }}" -backend-config="prefix=terraform/gke"
        working-directory: infra/terraform/gke

      - name: Terraform destroy
        run: terraform destroy -auto-approve -var-file=env.tfvars
        working-directory: infra/terraform/gke
